blank_issues_enabled: false
contact_links:
  - name: Dev channel on ESUP Rocket.Chat
    url: https://rocket.esup-portail.org/group/Avenirs_developpement
    about: For general questions or discussions related to development.